2:27:47:dig2:Warn:DEBUG MODE ON. Can be slow !
2:27:48:alg:Info:analyze ./programs/hola/17.dig.c
2:27:48:alg:Info:set seed to: 1493796467.79 (test 5)
2:27:48:alg:Info:check reachability
2:27:48:alg:Info:gen eqts at 1 locs: l19 (int k, int n)
2:27:57:alg:Info:1 invs:
l19: (n*n*n) - 6*k - n + 6 == 0
2:27:57:alg:Info:gen ieqs at 1 locs: l19 (int k, int n)
2:27:57:alg:Info:1 locs: check upperbounds for 8 terms
Traceback (most recent call last):
  File "dig2.py", line 71, in <module>
    doEqts=not args.noeqts, doIeqs=not args.noieqs)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 407, in start
    if doIeqs: _gen('ieqs')        
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 399, in _gen
    invs = solver.gen(deg, traces, inps)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 252, in gen
    _ = self.getTracesAndUpdate(newInps, traces)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 68, in getTracesAndUpdate
    assert inps
AssertionError
