2:47:7:dig2:Warn:DEBUG MODE ON. Can be slow !
2:47:8:alg:Info:analyze ./programs/hola/21.dig.c
2:47:8:alg:Info:set seed to: 1493797627.09 (test 32)
2:47:8:alg:Info:check reachability
2:47:8:alg:Info:gen eqts at 1 locs: l27 (int k, int n, int j, int v)
Traceback (most recent call last):
  File "dig2.py", line 71, in <module>
    doEqts=not args.noeqts, doIeqs=not args.noieqs)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 406, in start
    if doEqts: _gen('eqts')
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 399, in _gen
    invs = solver.gen(deg, traces, inps)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 193, in gen
    initrs = [self.getInitTraces(loc, deg, traces, inps) for loc in traces]
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 124, in getInitTraces
    assert newTraces[loc]
KeyError: 'l27'
