4:29:24:dig2:Warn:DEBUG MODE ON. Can be slow !
4:29:25:alg:Info:analyze ./programs/hola/28.dig.c
4:29:25:alg:Info:set seed to: 1493803764.39 (test 70)
4:29:25:alg:Info:check reachability
4:29:25:alg:Info:gen eqts at 1 locs: l22 (int y, int n, int x)
Traceback (most recent call last):
  File "dig2.py", line 71, in <module>
    doEqts=not args.noeqts, doIeqs=not args.noieqs)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 406, in start
    if doEqts: _gen('eqts')
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 399, in _gen
    invs = solver.gen(deg, traces, inps)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 193, in gen
    initrs = [self.getInitTraces(loc, deg, traces, inps) for loc in traces]
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 124, in getInitTraces
    assert newTraces[loc]
KeyError: 'l22'
